spring:
  jpa:
    hibernate:
      ddl-auto: 'create-drop'
      show-sql: true
  datasource:
    url: jdbs:postgresql://localhost:5432/shop
    username: admin
    password: 25669
  flyway:
    baseline-on-migrate: true